services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javalin-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ecommerce
      - DB_USER=postgres      # Adicionado
      - DB_PASSWORD=password  # Adicionado (precisa ser igual ao POSTGRES_PASSWORD abaixo)
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/sql/scripts.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: